trigger:
- main

pool:
  vmImage: 'windows-latest'

steps:

- task: UseDotNet@2
  displayName: 'Install .NET SDK'
  inputs:
    packageType: 'sdk'
    version: '8.0.x'

- script: dotnet restore src/Web/Web.csproj
  displayName: 'Restore Packages'

- script: dotnet build src/Web/Web.csproj --configuration Release --no-restore
  displayName: 'Build Application'
